// <auto-generated />
using APILabb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APILabb.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APILabb.Models.Connection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("InterestID")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("InterestID");

                    b.HasIndex("UserID");

                    b.ToTable("Connections");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            InterestID = 1,
                            URL = "https://www.youtube.com",
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            InterestID = 1,
                            URL = "https://www.google.com",
                            UserID = 1
                        },
                        new
                        {
                            ID = 3,
                            InterestID = 2,
                            URL = "https://www.google.com",
                            UserID = 1
                        },
                        new
                        {
                            ID = 4,
                            InterestID = 3,
                            URL = "https://www.microsoft.com",
                            UserID = 3
                        },
                        new
                        {
                            ID = 5,
                            InterestID = 4,
                            URL = "https://www.github.com",
                            UserID = 4
                        });
                });

            modelBuilder.Entity("APILabb.Models.Interest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            InterestName = "Programming"
                        },
                        new
                        {
                            ID = 2,
                            InterestName = "Cooking"
                        },
                        new
                        {
                            ID = 3,
                            InterestName = "Traveling"
                        },
                        new
                        {
                            ID = 4,
                            InterestName = "Sports"
                        });
                });

            modelBuilder.Entity("APILabb.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Alice",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Bob",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Charlie",
                            PhoneNumber = "5555555555"
                        },
                        new
                        {
                            ID = 4,
                            Name = "David",
                            PhoneNumber = "1111111111"
                        });
                });

            modelBuilder.Entity("APILabb.Models.Connection", b =>
                {
                    b.HasOne("APILabb.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APILabb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
